-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CAMPTINA
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CAMPTINA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CAMPTINA` DEFAULT CHARACTER SET utf8 ;
USE `CAMPTINA` ;

-- -----------------------------------------------------
-- Table `CAMPTINA`.`CATEGORIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CAMPTINA`.`CATEGORIA` (
  `ID_CATEGORIA` INT NOT NULL AUTO_INCREMENT,
  `NOM` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID_CATEGORIA`),
  UNIQUE INDEX `ID_CATEGORIA_UNIQUE` (`ID_CATEGORIA` ASC) VISIBLE,
  UNIQUE INDEX `NOM_UNIQUE` (`NOM` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CAMPTINA`.`APAT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CAMPTINA`.`APAT` (
  `ID_APAT` INT NOT NULL AUTO_INCREMENT,
  `NOM` VARCHAR(50) NOT NULL,
  `DESCRIPCIO` VARCHAR(100) NULL,
  `ID_CATEGORIA` INT NOT NULL,
  PRIMARY KEY (`ID_APAT`),
  UNIQUE INDEX `idAPAT_UNIQUE` (`ID_APAT` ASC) VISIBLE,
  INDEX `ID_CATEGORIA_idx` (`ID_CATEGORIA` ASC) VISIBLE,
  CONSTRAINT `FK_APAT_CATEGORIA`
    FOREIGN KEY (`ID_CATEGORIA`)
    REFERENCES `CAMPTINA`.`CATEGORIA` (`ID_CATEGORIA`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CAMPTINA`.`MENU`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CAMPTINA`.`MENU` (
  `ID_MENU` INT NOT NULL AUTO_INCREMENT,
  `NOM` VARCHAR(50) NOT NULL,
  `PREU` INT NULL,
  `ACTIU` TINYINT NOT NULL COMMENT 'La columna ACTIU indic asi el menú es pot selecciona. 0 (fals) o 1 (verdader)',
  PRIMARY KEY (`ID_MENU`),
  UNIQUE INDEX `ID_MENU_UNIQUE` (`ID_MENU` ASC) VISIBLE,
  UNIQUE INDEX `NOM_UNIQUE` (`NOM` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CAMPTINA`.`TORN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CAMPTINA`.`TORN` (
  `ID_TORN` INT NOT NULL AUTO_INCREMENT,
  `DESCRIPCIO` VARCHAR(100) NOT NULL,
  `HORA_INICI` TIME NULL,
  `HORA_FI` TIME NULL,
  `AFORAMENT_MAXIM` INT NULL,
  PRIMARY KEY (`ID_TORN`),
  UNIQUE INDEX `ID_TORN_UNIQUE` (`ID_TORN` ASC) VISIBLE,
  UNIQUE INDEX `DESCRIPCIO_UNIQUE` (`DESCRIPCIO` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CAMPTINA`.`ROL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CAMPTINA`.`ROL` (
  `ID_ROL` INT NOT NULL AUTO_INCREMENT,
  `NOM` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_ROL`),
  UNIQUE INDEX `ID_ROL_UNIQUE` (`ID_ROL` ASC) VISIBLE,
  UNIQUE INDEX `NOM_UNIQUE` (`NOM` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CAMPTINA`.`USUARI`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CAMPTINA`.`USUARI` (
  `ID_USUARI` INT NOT NULL AUTO_INCREMENT,
  `NOM` VARCHAR(45) NULL,
  `COGNOM1` VARCHAR(45) NULL,
  `COGNOM2` VARCHAR(45) NULL,
  `ID_ROL` INT NOT NULL,
  `EMAIL` VARCHAR(100) NULL,
  PRIMARY KEY (`ID_USUARI`),
  UNIQUE INDEX `ID_USUARI_UNIQUE` (`ID_USUARI` ASC) VISIBLE,
  INDEX `FK_ID_ROL_idx` (`ID_ROL` ASC) VISIBLE,
  UNIQUE INDEX `EMAIL_UNIQUE` (`EMAIL` ASC) VISIBLE,
  CONSTRAINT `FK_USUARI_ROL`
    FOREIGN KEY (`ID_ROL`)
    REFERENCES `CAMPTINA`.`ROL` (`ID_ROL`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CAMPTINA`.`MENU_APATS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CAMPTINA`.`MENU_APATS` (
  `ID_MENU` INT NOT NULL,
  `ID_APAT` INT NOT NULL,
  PRIMARY KEY (`ID_MENU`, `ID_APAT`),
  INDEX `FK_ID_APAT_idx` (`ID_APAT` ASC) VISIBLE,
  CONSTRAINT `FK_MENUAPAT_MENU`
    FOREIGN KEY (`ID_MENU`)
    REFERENCES `CAMPTINA`.`MENU` (`ID_MENU`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_MENUAPAT_APAT`
    FOREIGN KEY (`ID_APAT`)
    REFERENCES `CAMPTINA`.`APAT` (`ID_APAT`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CAMPTINA`.`RESERVA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CAMPTINA`.`RESERVA` (
  `ID_RESERVA` INT NOT NULL AUTO_INCREMENT,
  `ID_USUARI` INT NOT NULL,
  `ID_TORN` INT NOT NULL,
  `ID_MENU` INT NOT NULL,
  `ID_PRIMER` INT NOT NULL,
  `ID_SEGON` INT NOT NULL,
  `ID_POSTRE` INT NOT NULL,
  `DATA` DATE NOT NULL,
  PRIMARY KEY (`ID_RESERVA`, `ID_USUARI`, `ID_TORN`, `ID_MENU`, `DATA`),
  UNIQUE INDEX `ID_RESERVA_UNIQUE` (`ID_RESERVA` ASC) VISIBLE,
  INDEX `FK_RESERVA_USUARI_idx` (`ID_USUARI` ASC) VISIBLE,
  INDEX `FK_RESERVA_TORN_idx` (`ID_TORN` ASC) VISIBLE,
  INDEX `FK_RESERVA_MENU_idx` (`ID_MENU` ASC) VISIBLE,
  INDEX `FK_RESERVA_PRIMER_idx` (`ID_PRIMER` ASC) VISIBLE,
  INDEX `FK_RESERVA_SEGON_idx` (`ID_SEGON` ASC) VISIBLE,
  INDEX `FK_RESERVA_POSTRE_idx` (`ID_POSTRE` ASC) VISIBLE,
  CONSTRAINT `FK_RESERVA_USUARI`
    FOREIGN KEY (`ID_USUARI`)
    REFERENCES `CAMPTINA`.`USUARI` (`ID_USUARI`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_RESERVA_TORN`
    FOREIGN KEY (`ID_TORN`)
    REFERENCES `CAMPTINA`.`TORN` (`ID_TORN`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_RESERVA_MENU`
    FOREIGN KEY (`ID_MENU`)
    REFERENCES `CAMPTINA`.`MENU` (`ID_MENU`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_RESERVA_PRIMER`
    FOREIGN KEY (`ID_PRIMER`)
    REFERENCES `CAMPTINA`.`APAT` (`ID_APAT`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_RESERVA_SEGON`
    FOREIGN KEY (`ID_SEGON`)
    REFERENCES `CAMPTINA`.`APAT` (`ID_APAT`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_RESERVA_POSTRE`
    FOREIGN KEY (`ID_POSTRE`)
    REFERENCES `CAMPTINA`.`APAT` (`ID_APAT`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `CAMPTINA`.`CATEGORIA`
-- -----------------------------------------------------
START TRANSACTION;
USE `CAMPTINA`;
INSERT INTO `CAMPTINA`.`CATEGORIA` (`ID_CATEGORIA`, `NOM`) VALUES (1, 'PRIMER');
INSERT INTO `CAMPTINA`.`CATEGORIA` (`ID_CATEGORIA`, `NOM`) VALUES (2, 'SEGON');
INSERT INTO `CAMPTINA`.`CATEGORIA` (`ID_CATEGORIA`, `NOM`) VALUES (3, 'POSTRE');

COMMIT;


-- -----------------------------------------------------
-- Data for table `CAMPTINA`.`APAT`
-- -----------------------------------------------------
START TRANSACTION;
USE `CAMPTINA`;
INSERT INTO `CAMPTINA`.`APAT` (`ID_APAT`, `NOM`, `DESCRIPCIO`, `ID_CATEGORIA`) VALUES (1, 'PLAT 1', 'EXEMPLE', 1);
INSERT INTO `CAMPTINA`.`APAT` (`ID_APAT`, `NOM`, `DESCRIPCIO`, `ID_CATEGORIA`) VALUES (2, 'PLAT 2', 'EXEMPLE', 2);
INSERT INTO `CAMPTINA`.`APAT` (`ID_APAT`, `NOM`, `DESCRIPCIO`, `ID_CATEGORIA`) VALUES (3, 'PLAT 3', 'EXEMPLE', 3);

COMMIT;


-- -----------------------------------------------------
-- Data for table `CAMPTINA`.`MENU`
-- -----------------------------------------------------
START TRANSACTION;
USE `CAMPTINA`;
INSERT INTO `CAMPTINA`.`MENU` (`ID_MENU`, `NOM`, `PREU`, `ACTIU`) VALUES (1, 'MENU', 6, true);

COMMIT;


-- -----------------------------------------------------
-- Data for table `CAMPTINA`.`TORN`
-- -----------------------------------------------------
START TRANSACTION;
USE `CAMPTINA`;
INSERT INTO `CAMPTINA`.`TORN` (`ID_TORN`, `DESCRIPCIO`, `HORA_INICI`, `HORA_FI`, `AFORAMENT_MAXIM`) VALUES (1, 'PRIMER TORN', '12:45', '13:30', 50);
INSERT INTO `CAMPTINA`.`TORN` (`ID_TORN`, `DESCRIPCIO`, `HORA_INICI`, `HORA_FI`, `AFORAMENT_MAXIM`) VALUES (2, 'SEGON TORN', '13:30', '14:15', 50);
INSERT INTO `CAMPTINA`.`TORN` (`ID_TORN`, `DESCRIPCIO`, `HORA_INICI`, `HORA_FI`, `AFORAMENT_MAXIM`) VALUES (3, 'TERCER TORN', '14:15', '15:00', 50);

COMMIT;


-- -----------------------------------------------------
-- Data for table `CAMPTINA`.`ROL`
-- -----------------------------------------------------
START TRANSACTION;
USE `CAMPTINA`;
INSERT INTO `CAMPTINA`.`ROL` (`ID_ROL`, `NOM`) VALUES (1, 'GESTOR');
INSERT INTO `CAMPTINA`.`ROL` (`ID_ROL`, `NOM`) VALUES (2, 'TREBALLADOR');

COMMIT;


-- -----------------------------------------------------
-- Data for table `CAMPTINA`.`USUARI`
-- -----------------------------------------------------
START TRANSACTION;
USE `CAMPTINA`;
INSERT INTO `CAMPTINA`.`USUARI` (`ID_USUARI`, `NOM`, `COGNOM1`, `COGNOM2`, `ID_ROL`, `EMAIL`) VALUES (1, 'GESTOR', NULL, NULL, 1, NULL);

COMMIT;

