-- ACTUALITZACIÓ BASE DE DADES CORRESPONENT A L'SPRINT TEA4

--modificar el nom de la columna DESCRIPCIO per NOM a la taula TORN i el limit de 100 a 25.
ALTER TABLE CAMPTINA.TORN RENAME COLUMN DESCRIPCIO TO NOM;
ALTER TABLE CAMPTINA.TORN MODIFY COLUMN NOM VARCHAR(25);
COMMIT;
